ASPNETCORE_ENVIRONMENT=Development
ASPNETCORE_URLS=http://localhost:5002

# Put your database DSN/connection string here (format depends on your DB/provider)
DATABASE_DSN=root:88888888@tcp(127.0.0.1:3306)/dotnet_users?charset=utf8mb4&parseTime=True"

